databases:
    oms_prod_replica:
        host: oms-prod-psql-replica.porter.in
        port: 5432
        user: murtaza_jalal
        password: 41cU7PFrL3y9QeKsaJq5OgSdQik=
        database: porter_order_production
        
    oms_prod_snapshot:
        host: oms-prod-psql-snapshot.data.porter.in
        port: 5432
        user: murtaza_jalal
        password: 41cU7PFrL3y9QeKsaJq5OgSdQik=
        database: porter_order_production

    sfms:
        host: sfms-prod-psql-replica.porter.in
        port: 5432
        database: sfms_production
        user: murtaza_jalal
        password: 8DDmhJYTMaq0xcbshZu0yWORh84=
